AUTH_METHOD_LOCAL_PASSWORD = "LOCAL_PASSWORD"

ACCOUNT_ACTIVE = "ACTIVE"
ACCOUNT_DISABLED = "DISABLED"

AUTHENTICATION_REQUIRED = "AUTHENTICATION_REQUIRED"
AUTHENTICATION_FAILED = "AUTHENTICATION_FAILED"
SESSION_EXPIRED = "SESSION_EXPIRED"
CSRF_VALIDATION_FAILED = "CSRF_VALIDATION_FAILED"
ACTOR_WORKER_REQUIRED = "ACTOR_WORKER_REQUIRED"
ACTOR_WORKER_INACTIVE = "ACTOR_WORKER_INACTIVE"
PASSWORD_CHANGE_REQUIRED = "PASSWORD_CHANGE_REQUIRED"
PASSWORD_POLICY_FAILED = "PASSWORD_POLICY_FAILED"
IDENTITY_CONFLICT = "IDENTITY_CONFLICT"
